### ISSUE TITLE
backend.js:6 THREE.BufferAttribute: .setArray has been removed. Use BufferGeometry .setAttribute to replace/resize attribute buffers

### ISSUE THREAD

**Issue by arpu** [lojjic/aframe-troika-text#1]
with new threejs v110

**Comment by arpu** [comment]
looks like a version bumop for  "troika-3d-text": "^0.15.2"  to 0.15.5 should help?

**Comment by lojjic** [comment]
Good catch, thanks. You're right, newer troika-3d-text versions have that particular fix and a bump here _should_ be safe. Although, Troika's "blessed" threejs versions (defined here: https://github.com/protectwise/troika/blob/master/packages/troika-3d/package.json) are still just up to r109, I haven't had a chance to fully test 110 yet.

How are you using r110 with AFrame, out of curiosity? Aren't they still locked to their forked r109?

**Comment by arpu** [comment]
i use my own aframe build with included threejs dev source for testing

**Comment by arpu** [comment]
what i have tested now is  using trokia build textmesh-standalone.esm.js
and use the aframe-component from here 

but with this i get this strange problem 

```core:a-node:error Failure loading node:   Error: `Entity.setObject3D` was called with an object that was not an instance of THREE.Object3D.
    at HTMLElement.setObject3D (a-entity.js?5e89:148)
    at NewComponent.init (troika-text.js?e78b:51)
```
its from the line textEntity.setObject3D("mesh", textMesh);

but textMesh looks fine 
```
"{"metadata":{"version":4.5,"type":"Object","generator":"Object3D.toJSON"},"geometries":[{"uuid":"6A13E2FE-34BD-4040-AF40-1DE614F9FC2C","type":"InstancedBufferGeometry","data":{"attributes":{"position":{"itemSize":3,"type":"Float32Array","array":[0,1,0,1,1,0,0,0,0,1,0,0],"normalized":false},"normal":{"itemSize":3,"type":"Float32Array","array":[0,0,1,0,0,1,0,0,1,0,0,1],"normalized":false},"uv":{"itemSize":2,"type":"Float32Array","array":[0,1,1,1,0,0,1,0],"normalized":false}},"index":{"type":"Uint16Array","array":[0,2,1,2,3,1]},"boundingSphere":{"center":[0,0,0],"radius":0}}}],"materials":[{"uuid":"70D064C8-A9C6-48E3-8DE9-8DAD4DF8AC69","type":"MeshBasicMaterial","color":16777215,"side":2,"transparent":true,"depthFunc":3,"depthTest":true,"depthWrite":true}],"object":{"uuid":"B8AFDC2D-9876-49C2-ADDC-2F98FD980224","type":"Mesh","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"geometry":"6A13E2FE-34BD-4040-AF40-1DE614F9FC2C","material":"70D064C8-A9C6-48E3-8DE9-8DAD4DF8AC69"}}```

**Comment by arpu** [comment]
ok i think this problem comes from different treeversions  aframe component use the global a frame THREE  and the  textmesh-standalone.esm.js use 
```
import {
  DataTexture,
  LuminanceFormat,
  LinearFilter,
  PlaneBufferGeometry,
  Vector3,
  InstancedBufferGeometry,
  InstancedBufferAttribute,
  Sphere,
  Vector4,
  MeshBasicMaterial,
  DoubleSide,
  Matrix4,
  Plane,
  Mesh
} from "three";
```

**Comment by lojjic** [comment]
Yes that sounds like multiple versions of THREE being loaded. This _should_ be taken care of by the build script that produces `dist/aframe-troika-text.js` -- that expects to use the global THREE that aframe provides.

**Comment by arpu** [comment]
ah thx i see!

**Comment by arpu** [comment]
i think this can be closed, aframe still using threejs v109, maybe  i can reopen it if aframe move to newer version

**Comment by lojjic** [comment]
Sounds good, thanks. I'll try to update the dependency anyway before then.
