### ISSUE TITLE
Feature: preloading font in a-assets

### ISSUE THREAD

**Issue by lojjic** [lojjic/aframe-troika-text#19]
To avoid noticeable rendering delays when first using a font, we should add preloading capability. You can already handle the font file itself using `<a-asset-item src="fontfile.woff">`, but we can additionally allow pregeneration of glyph SDFs using the [`preloadFont()` utility](https://github.com/protectwise/troika/tree/master/packages/troika-3d-text#preloading) in troika-3d-text.

**Comment by lijualivenow** [comment]
yes <a-asset-item src="fontfile.woff"> feature is required. Other features are very good.

**Comment by kfarr** [comment]
Yeah I was trying to figure out the "right" way to reference the same font across troika text entities using the same custom font, seems like asset loader would help here?

**Comment by lojjic** [comment]
>...  `font="#my-font"`

I can see how that would be nice. I'll keep that in mind if/when I ever get to this feature.

> In the meantime it sounds like you can use the asset loader for a font and that will at least make sure the font is loaded during scene loading screen and then subsequent references are cached?

Yes, that's true. All instances that reference the same font file share a single loading state and SDF texture. The font file will be loaded and the SDF will be generated per character on first usage, so there can be a period when text should be visible but it's still waiting on those things. This feature would help minimize that delay, by letting aframe's asset loading system wait for the font file to be loaded (and ideally an initial set of of characters to be generated) before entering the scene.

**Comment by lojjic** [comment]
Thanks to @msub2 contributing the `font="#assetId"` support in PR #57, I believe this is now satisfied. It doesn't pregenerate SDFs, but since troika-three-text now does that on the GPU it's super fast anyway and shouldn't be noticeable in the vast majority of cases.

**Comment by Utopiah** [comment]
Hi, I'm trying to work offline so specifying the font path should work yet 

```html
            <a-asset-item id="font" src="roboto.woff"></a-asset-item>
      </a-assets>
...
      <a-troika-text target value="jxr qs a-sphere sa color blue" font="#font"></a-troika-text>
```

does not while `<a-troika-text target value="jxr qs a-sphere sa color blue" font="roboto.woff"` does.

What am I missing?

**Comment by dzg** [comment]
> What am I missing?
> 
> Edit: I was missing the updated version since that PR, my bad, all good! :D

I'm having the same issue – what is the fix? Which PR? Thanks

**Comment by Utopiah** [comment]
I was using a version predating the PR. You seem to rely on a CDN so probably unrelated.
