### ISSUE TITLE
Using another font in troika-text

### ISSUE THREAD

**Issue by tomasbrownnz** [lojjic/aframe-troika-text#20]
When trying to load a new font URL into the text component I am getting an error that stops the text from rendering. When I use the regular font the render works fine, but when I change the font to Google Font's NotoSansSC and try to render some text (Hello), I get this error:

troika-worker-utils.esm.js:470 
Uncaught (in promise) Error: Error in worker callModule call: Cannot read property '41' of undefined
    at l.<computed> (troika-worker-utils.esm.js:470)
    at Worker.t.onmessage (troika-worker-utils.esm.js:456)

The NotoSans font file is the .otf file directly downloaded from google fonts, it seems to load the font fine but it is when I load in a new text value that breaks the render.

**Comment by tomasbrownnz** [comment]
This error occurs when I load the font from a local .otf file, when I use google font's embedded URL such as 

https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300&display=swap 

The error changes to:

fee9b3dc-bd79-4d73-918a-7900c07daab3:5 
Failure loading font https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300&display=swap; trying fallback TypeError: Cannot read property 'indexToLocFormat' of undefined

**Comment by lojjic** [comment]
That google fonts URL in your second comment is not a font file, that's a CSS file, so it makes sense why that can't be parsed.

Are you able to link me directly to the .otf file you're trying to use?

**Comment by tomasbrownnz** [comment]
In the first instance I was using the .otf file that was supplied with this download link:

https://fonts.google.com/download?family=Noto%20Sans%20SC

I had some success using the .wof file that is downloaded using this site:

https://google-webfonts-helper.herokuapp.com/fonts/noto-sans-sc?subsets=chinese-simplified,latin

But only with the Noto Sans font, I need the Noto Sans SC font as I need to include Chinese characters in my render.

Investigating further I think it is the handling of any font with Chinese characters that is causing this issue. I wonder if you have had any success with rendering Chinese characters?

**Comment by lojjic** [comment]
Thank you for that download link; I'm able to reproduce the issue from there.

It appears that this particular font file is missing a `loca` table, which the underlying font parser ([Typr.js](https://github.com/photopea/Typr.js)) errors on. This seems like a bug in Typr, but I'll try to verify that.

I do know that others have been able to render Chinese characters, using other fonts I presume.

**Comment by tomasbrownnz** [comment]
Okay cool, thank you very much! I will reach out to A-Frame's Slack channel to see if anyone can recommend a font I can use.

**Comment by lojjic** [comment]
OK, I think this is a bug in troika-3d-text, not the underlying font parser. Apparently there is a special code path that's required for extracting glyph outlines from fonts with a `CFF` table, which troika isn't invoking.

I'm going to move this issue over to the troika repository so I can address it there.

**Comment by lojjic** [comment]
@tomasbrownnz Please try the 0.3.2 version I just released. I believe this should fix that font for you.

**Comment by lojjic** [comment]
Test on my machine using that font:

![image](https://user-images.githubusercontent.com/138124/80935777-71f3e000-8d8b-11ea-921d-13958dea8b15.png)

**Comment by tomasbrownnz** [comment]
Nice @lojjic works perfectly! Thanks for the quick fix :)
