### ISSUE TITLE
update troika-3d-text for three.js r117

### ISSUE THREAD

**Issue by arpu** [lojjic/aframe-troika-text#25]
would be nice to get the updated troika-3d-text package for the aframe build ( for three r117)

**Comment by lojjic** [comment]
Thanks for the reminder, I'll try to put out a release today.

The current version does actually work with r117, right? Just logs some console warnings?

**Comment by arpu** [comment]
yes exactly

**Comment by lojjic** [comment]
published v0.3.4

**Comment by arpu** [comment]
thx!
