### ISSUE TITLE
ZOffset like aframe text component 

### ISSUE THREAD

**Issue by arpu** [lojjic/aframe-troika-text#3]
HI,

would it be possible to add some zOffset like text aframe component has it? 
https://aframe.io/docs/0.9.0/components/text.html#properties_zoffset

**Comment by lojjic** [comment]
Is this specifically for using it with a `geometry` plane component as background to avoid z-fighting?

Troika's TextMesh has a `depthOffset` property (apparently undocumented - oops!) which is just a shortcut for THREE.Material's [polygonOffset/polygonOffsetUnits/polygonOffsetFactor](https://threejs.org/docs/#api/en/materials/Material.polygonOffset) properties, and is intended as a solution for z-fighting. But it's not currently exposed through the aframe component. That should be a simple addition though.

In the meantime maybe use a separate <a-troika-text> entity and give it a `z` position slightly in front of the geometry entity?

**Comment by arpu** [comment]
yeahh this will work! thx

**Comment by lojjic** [comment]
The `depthOffset` attribute is now exposed.
