### ISSUE TITLE
Some Properties are Not Working

### ISSUE THREAD

**Issue by lijualivenow** [lojjic/aframe-troika-text#40]
Some properties are not working like fontSize, outlineColor, outlineWidth

please check the sample code

https://glitch.com/~aframe-troika-text

**Comment by lojjic** [comment]
Attributes on the primitive must be dashed: `outline-width` not `outlineWidth`.

Properties in the CSS-like component string are case sensitive, so `outlineWidth` not `outlinewidth`.

This seems to fix both your issues; reopen if you still see a problem.
