### ISSUE TITLE
Not Working On ios 14.7.1

### ISSUE THREAD

**Issue by pranav-pavithran** [lojjic/aframe-troika-text#54]
troika text is not displayed at all in my iPhone 7 ( ios 14.7.1) , tried both primitive & component methods, "Could not get webgl version 2 " error was there. So I have enabled webgl2 in safari's settings, But still text wasn't showing up.

a-text is working fine

**Comment by lojjic** [comment]
Apologies, I forgot to republish with the troika-three-text 0.46.4 patch, which contains the fix for older iOS versions. It's now published as 0.7.1. Thanks for letting me know!
