### ISSUE TITLE
Text is wrecked on iOS

### ISSUE THREAD

**Issue by dzg** [lojjic/aframe-troika-text#67]
I was very excited for this component, but this is what I'm getting on iOS (both Safari and Chrome):

![](https://user-images.githubusercontent.com/466557/217404613-957789d4-29b5-46d9-b638-f5b2452f2a81.png)

On macOS it looks fine:

![](https://user-images.githubusercontent.com/466557/217404641-490f3448-d556-41ad-90d3-0d6513242d7b.png)

Any idea why?

**Comment by lojjic** [comment]
That looks very much like an [old bug](https://github.com/protectwise/troika/issues/88) which has been fixed for some time.

Given this and your other issue with a-asset-item not working, it really sounds like you may have an old version of aframe-troika-text running. Is it possible you have two separate versions being loaded from different places, and the older one is winning?

**Comment by dzg** [comment]
Yes, I think you're right ... I switched to aframe 1.3.0 and the above rendered properly. Now I have to go back and reform old code ... sigh ... 

Thank you
