### ISSUE TITLE
Inconsistent bounding boxes

### ISSUE THREAD

**Issue by Utopiah** [lojjic/aframe-troika-text#70]
Hi,

I tried to repeat https://github.com/AdaRoseCannon/aframe-htmlmesh/issues/4 here but it didn't work. I tried making a bounding box but the geometry was very different from what I expected, namely a square rather than a rectangle.

In the screenshot below I can show one that worked, the lower one, and one that didn't, despite using the same code 

`el = new THREE.BoxHelper( document.getElementById("locationreload").object3D.children[0], 0x00ff00 ); AFRAME.scenes[0].object3D.add(el)`

![image](https://user-images.githubusercontent.com/1076655/228896114-c81c314a-e0c5-499b-a054-50476bc00906.png)

Is somehow forcing a `sync()` necessary? Did I miss a step? Note that I did that via the console and seconds after the scene was displayed so I'm relatively confident everything was loaded, at least displayed as it should. I also noticed https://github.com/lojjic/aframe-troika-text/issues/38 before but again, I'm not doing it right after adding the element so not sure it would relevant here.

Anyway, what is the recommended way to add a background behind an entire element or part of it?

PS: I noticed https://protectwise.github.io/troika/troika-three-text/#carets-and-selection-ranges that could later on be useful to highlight words or lines but didn't dive in there before being able to have the entire element.

**Comment by Utopiah** [comment]
The AFrame inspector also makes the square bounding boxes on element selection

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1076655/228899883-5ba6b6b1-1d8c-4b52-9a68-b144ef3f09b7.png">

**Comment by Utopiah** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/1076655/228902815-8b53e88b-b0d7-4521-a76b-2f0cace759b0.png">

If I change value from 12345 to 1 the bounding box does seems like it is update properly so... maybe unrelated, maybe a threejs/AFrame boxhelper issue. Leaving this open for now as I still investigate.

**Comment by Utopiah** [comment]
Seems it's a boxhelper issue as the boundingbox itself seems fine and creating a boxgeometry from it works as expected. Less convenient but sufficient to add a background.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1076655/228907826-34ecf49c-09ed-43a2-91f5-12e7035dcef8.png">

**Comment by lojjic** [comment]
My suspicion is the BoxHelper was reading the geometry.boundingBox before the text sync() callback is complete and not getting updated afterward? 🤷

**Comment by lijualivenow** [comment]
I am facing the same issue, the bounding box is not getting properly

**Comment by Utopiah** [comment]
@lijualivenow try checking 1000ms after creating the entity and if it does make a difference tried indeed `.sync()` and check after, iirc worked for me.

**Comment by lijualivenow** [comment]
@Utopiah, after 1000ms it's working, thank you.
