### ISSUE TITLE
How to get height of a-troika-text?

### ISSUE THREAD

**Issue by Atlinx** [lojjic/aframe-troika-text#75]
Is it possible to fetch the height of an `a-troika-text` primitive that's wrapping? I have a background for the text that I'd like to resize to the entire text's current height.

**Comment by lojjic** [comment]
You can access the underlying Text object via `element.troikaTextMesh` (not publicly documented, its name could change in the future), from there you should be able to subscribe to synccomplete events and update your background from the info provided in `.textRenderInfo`.

**Comment by Atlinx** [comment]
> You can access the underlying Text object via `element.troikaTextMesh` (not publicly documented, its name could change in the future), from there you should be able to [subscribe to synccomplete events](https://protectwise.github.io/troika/troika-three-text/#handling-asynchronous-updates) and update your background from the info provided in `.textRenderInfo`.

Thanks, that did the trick! :)
